language: node_js
node_js:
  - "node"
addons:
  chrome: stable # have Travis install chrome stable.
cache:
  npm: true
  directories:
    - node_modules
install:
  - npm install
  - npm run-script build
script:
  - npm test
